version: '3'
services:
  sentidos-db:
    image: postgres:12.8-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - sentidosdb-data:/var/lib/postgresql/data
  sentidos-api:
    image: ghcr.io/morales-ivan/sentidos-api-dev:latest
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:?err}
      - ADMIN_USERNAME=${ADMIN_USERNAME:?err}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:?err}
volumes:
  sentidosdb-data:
    driver: local