logging:
    level:
        org:
            hibernate:
                tool:
                    hbm2ddl: DEBUG
            springframework:
                security: DEBUG
spring:
    datasource:
        url: jdbc:postgresql://sentidos-db:5432/sentidos
        driverClassName: org.postgresql.Driver
        username: sirius
        password: BlackPanther
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

aws:
    endpoint: https://s3.amazonaws.com
    accessKey: AKIASJORA25PUZVPFTNO
    secretKey: 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
    region: us-east-1
    bucket: sentido-sinco
