logging:
    level:
        org:
            hibernate:
                tool:
                    hbm2ddl: DEBUG
            springframework:
                security: DEBUG
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sentidos
        driverClassName: org.postgresql.Driver
        username: sa
        password: password
    flyway:
        enabled: true
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
