CREATE ROLE sirius WITH
    LOGIN
    SUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'BlackPanther';

CREATE DATABASE sentidos;

GRANT ALL PRIVILEGES ON DATABASE sentidos TO sirius;